<div class="row">
    <h3 class="text-center">Windows PC</h3>
    <h4 class="text-center">Main Menu</h4>
    <p><b>User Name:</b> a Alias, or user name, you create along with a button to drop down more user names you've created, and then on the right side of the user names -- is another button with "->" symbol to create a new user name. No registration required.</p>
    <img src="img/information_page/ventrilo-usersetup.PNG" class="img-responsive img-grounded img-center" alt="ventrilo-usersetup.PNG" />
    <p><b>Setup User</b> window, as shown above, will allow you to create a user name for ventrilio. Can be anything you like, and all you have to do is click the "new" button.<b>Clone</b> will allow you duplicate names.<b>Delete</b> will delete the user name AND all the servers attached to it.<b>Phonetic</b> is what other users will hear when YOU connect to the server, or join/leave a channel.<b>Description</b> is a side note for yourself to see when you load ventrilo, and an example is shown in the image above next to the user's name in parentheses.<b>Work Dir</b> is where your saved files from ventrilo will be stored on the computer itself. Click the ? mark if you wish to change this save destination on your computer, and leave a note in the blank white box regarding it's location on the computer.</p>
    <p>For new users, all you have to do is click the "new" button and enter in ANY name you like. Then, the "Phonetic" shown in the image above means what Ventrilo will say to others when you join a channel, or leave a channel, or server.</p>
    <p><b>Server:</b> a Name you provide, along with a button to drop down a list of more servers that are named by  you, and have configured; if the server does not exist, then ventrilo will give you a timed out error message -- after 10 seconds of trying to connect.</p>
    <img src="img/information_page/ventrilo-usersetup.PNG" class="img-responsive img-grounded img-center" alt="ventrilo-serversetup.PNG" />
    <p><b>Select</b> is a list of servers you've configured in the past.<b>New</b> button is to create the server after the information was filled in below afterwards.<b>Clone</b> is if you want to copy this server information to a new name.<b>Delete</b> is to delete the current selected server.<b>Hostname or IP</b> is the information you need to enter in order to connect to a hosted ventrilo server.<b>Port</b> is a four digit number that specifies which port to access the server from, and if this number is incorrect then the server will time out.<b>Password</b> is a required if the admins of the server choose to have the server private, or non-public.<b>Default Channel</b> is when specified to auto join a specific channel when connecting to this server. Correct password to this channel must match, or the user has permission to access the channel in order for this to work.</p>
    <h4>Server Setup : Check boxes</h4>
    <ul class="list-group">
        <li class="list-group-item"></li>
    </ul>
    <p class="text-center"><b>Bindings:</b> an Advance Setting to create shortcuts for Ventrilo to use. More details on how to use this in the <a href="../views/information/ventrilo_content/Adv-Setup.php#vent-advsetup-binding">section</a>.</p>
    <img src="img/information_page/ventrilo-mainmenu.PNG" class="img-responsive img-grounded img-center" alt="ventrilo-mainmenu.PNG" />
</div>